name: Code Review Enforcer

on:
  pull_request:
    branches:
      - develop
      - release

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Require review
        uses: Automattic/action-required-review@v4.0.0
        with:
          reviewers: tripathirajan
          exempt-users: tripathirajan
